import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/src/context/AuthContext";
import { AiStylistChatProvider } from "@/src/components/ai/AiStylistChatProvider";
import { AiStylistFloatingVisibility } from "@/src/components/ai/AiStylistFloatingVisibility";
import { AiStylistChatModal } from "@/src/components/ai/AiStylistChatModal";
import ThemeRegistry from "@/src/components/ThemeRegistry/ThemeRegistry";
import HeaderVisibility from "@/src/components/layout/HeaderVisibility";
import { AppearanceProvider } from "@/src/context/AppearanceContext";
import Box from "@mui/material/Box";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppearanceProvider>
          <ThemeRegistry>
            <Box sx={{ minHeight: "100vh", bgcolor: "background.default" }}>
              <AuthProvider>
                <AiStylistChatProvider>
                  <HeaderVisibility>
                    <AiStylistFloatingVisibility>
                      {children}
                    </AiStylistFloatingVisibility>
                    <AiStylistChatModal />
                  </HeaderVisibility>
                </AiStylistChatProvider>
              </AuthProvider>
            </Box>
          </ThemeRegistry>
        </AppearanceProvider>
      </body>
    </html>
  );
}
